import { mockAnalysisResult } from "@/data/mockData";

/**
 * Generates a simple text-based "PDF" report as a downloadable .txt file.
 * In production, this would use a real PDF library or server-side generation.
 * For now, we create a clean formatted text document.
 */
export function downloadReport(data = mockAnalysisResult) {
  const lines: string[] = [];
  const hr = "─".repeat(60);

  lines.push("VALISEARCH — STARTUP ANALYSIS REPORT");
  lines.push(hr);
  lines.push("");

  // Overview
  lines.push("1. OVERVIEW");
  lines.push(hr);
  lines.push(`Score: ${data.idea_analysis.score}/10 — Verdict: ${data.idea_analysis.verdict}`);
  lines.push("");
  lines.push(data.idea_analysis.summary);
  lines.push("");
  lines.push("Key Insights:");
  data.idea_analysis.quickInsights.forEach((q) => lines.push(`  • ${q}`));
  lines.push("");

  // Validation
  lines.push("2. VALIDATION");
  lines.push(hr);
  lines.push(`Market Demand: ${data.validation.marketDemand}%`);
  lines.push(`Feasibility: ${data.validation.feasibility}%`);
  lines.push(`Innovation Score: ${data.validation.innovationScore}%`);
  lines.push("");
  lines.push("Risks:");
  data.validation.risks.forEach((r) => lines.push(`  [${r.severity.toUpperCase()}] ${r.label}`));
  lines.push("");
  lines.push("Strengths:");
  data.validation.strengths.forEach((s) => lines.push(`  • ${s}`));
  lines.push("");

  // Market
  lines.push("3. MARKET RESEARCH");
  lines.push(hr);
  lines.push(`TAM: ${data.market_research.tam} — ${data.market_research.tamDescription}`);
  lines.push(`SAM: ${data.market_research.sam} — ${data.market_research.samDescription}`);
  lines.push(`SOM: ${data.market_research.som} — ${data.market_research.somDescription}`);
  lines.push(`Growth Rate: ${data.market_research.growthRate} CAGR`);
  lines.push("");
  lines.push(data.market_research.growthOutlook);
  lines.push("");
  lines.push("Trends:");
  data.market_research.trends.forEach((t) => lines.push(`  • ${t}`));
  lines.push("");

  // Competitors
  lines.push("4. COMPETITOR ANALYSIS");
  lines.push(hr);
  data.competitor_analysis.forEach((c) => {
    lines.push(`${c.name}: ${c.description}`);
    lines.push(`  Strengths: ${c.strengths.join(", ")}`);
    lines.push(`  Weaknesses: ${c.weaknesses.join(", ")}`);
    lines.push("");
  });

  // Product
  lines.push("5. PRODUCT STRATEGY");
  lines.push(hr);
  lines.push("MVP Features:");
  data.product_strategy.mvpFeatures.forEach((f) => lines.push(`  ✓ ${f.feature}`));
  lines.push("");
  lines.push("Differentiators:");
  data.product_strategy.differentiationFeatures.forEach((f) => lines.push(`  ◆ ${f.feature}`));
  lines.push("");
  lines.push("Premium Features:");
  data.product_strategy.premiumFeatures.forEach((f) => lines.push(`  ★ ${f.feature}`));
  lines.push("");

  // Branding
  lines.push("6. BRANDING");
  lines.push(hr);
  lines.push(`Name Suggestions: ${data.branding.namesSuggestions.join(", ")}`);
  lines.push(`Tagline: ${data.branding.tagline}`);
  lines.push("");
  lines.push(`Positioning: ${data.branding.positioning}`);
  lines.push("");
  lines.push(`Brand Voice: ${data.branding.brandVoice}`);
  lines.push("");

  // Monetization
  lines.push("7. MONETIZATION");
  lines.push(hr);
  lines.push(`Model: ${data.monetization.pricingModel}`);
  lines.push("");
  data.monetization.tiers.forEach((t) => {
    lines.push(`${t.name} (${t.price})`);
    t.features.forEach((f) => lines.push(`  • ${f}`));
    lines.push("");
  });
  lines.push("Revenue Streams:");
  data.monetization.revenueStreams.forEach((r) => lines.push(`  • ${r}`));
  lines.push("");

  // GTM
  lines.push("8. GO-TO-MARKET");
  lines.push(hr);
  lines.push("Channels:");
  data.go_to_market.channels.forEach((c) => lines.push(`  • ${c.name}: ${c.description}`));
  lines.push("");
  lines.push("Launch Strategy:");
  data.go_to_market.launchStrategy.forEach((s) => lines.push(`  ${s}`));
  lines.push("");
  lines.push("Growth Strategies:");
  data.go_to_market.growthStrategies.forEach((g) => lines.push(`  • ${g}`));
  lines.push("");

  // Verdict
  lines.push("FINAL VERDICT");
  lines.push(hr);
  lines.push(`Recommendation: ${data.final_verdict.recommendation} (${data.final_verdict.confidence}% confidence)`);
  lines.push("");
  lines.push(data.final_verdict.summary);
  lines.push("");
  lines.push(hr);
  lines.push("Generated by ValiSearch — valisearch.com");

  // Download
  const content = lines.join("\n");
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "ValiSearch-Report.txt";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
